/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivateRouteImport } from './routes/private'
import { Route as HouseRouteImport } from './routes/house'
import { Route as CreditCardRouteImport } from './routes/credit-card'
import { Route as IndexRouteImport } from './routes/index'

const PrivateRoute = PrivateRouteImport.update({
  id: '/private',
  path: '/private',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseRoute = HouseRouteImport.update({
  id: '/house',
  path: '/house',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditCardRoute = CreditCardRouteImport.update({
  id: '/credit-card',
  path: '/credit-card',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/credit-card': typeof CreditCardRoute
  '/house': typeof HouseRoute
  '/private': typeof PrivateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/credit-card': typeof CreditCardRoute
  '/house': typeof HouseRoute
  '/private': typeof PrivateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/credit-card': typeof CreditCardRoute
  '/house': typeof HouseRoute
  '/private': typeof PrivateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/credit-card' | '/house' | '/private'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/credit-card' | '/house' | '/private'
  id: '__root__' | '/' | '/credit-card' | '/house' | '/private'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreditCardRoute: typeof CreditCardRoute
  HouseRoute: typeof HouseRoute
  PrivateRoute: typeof PrivateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/private': {
      id: '/private'
      path: '/private'
      fullPath: '/private'
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/house': {
      id: '/house'
      path: '/house'
      fullPath: '/house'
      preLoaderRoute: typeof HouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-card': {
      id: '/credit-card'
      path: '/credit-card'
      fullPath: '/credit-card'
      preLoaderRoute: typeof CreditCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreditCardRoute: CreditCardRoute,
  HouseRoute: HouseRoute,
  PrivateRoute: PrivateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
